### ISSUE TITLE
extend input file format; make it into package

### ISSUE THREAD

**Issue by lisongmiller** [hkim89/fMulti-LMM#1]
Hi,

Thanks for developing this nice tool! 
I notice that it currently supports csv format as genotype input. Although it is possible to convert plink format, oxford format or VCF genotypes to csv, it is still a bit troublesome. So, I wonder if there is any plan for you to extend the input format and to make it into a package. Then it would a lot easier to use.

Best,
Song

**Comment by hkim89** [comment]
Thanks for your interest in the module.  fMulti-LMM does not require any particular file format.  It only requires Array{Float64} inputs, which means you can use .txt, or .csv, or whatever files you can read in Julia using Julia's generic function,'readdlm()'.   One way of extracting Array{Float64} from formats you mentioned above is to use SnpArrays.jl to read a plink format file in Julia and obtain corresponding Array{Float64} inputs for genotypes.  I have currently completed the code optimization of fMulti-LMM and will generate the package version within a month.  In terms of your suggestion, I may consider to add a functionality of reading such formats in the near future.

**Comment by lisongmiller** [comment]
Thanks for your reply. Looking forward to it!
